import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Home ({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <nav>
          <Link href='/' passHref> Home</Link>
          <Link href='/events' passHref>Events</Link>
          <Link href='/about-us' passHref>About Us</Link>

        </nav>
      </header>

      <main className={styles.main}>

        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>

            <Image width={300} height={300} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2> <p>{ev.description}</p>

          </Link>

        ))}

      </main>

      <footer className={styles.footer}>
        <p>2022 Time to Code - A Project with js</p>
      </footer>
    </div>
  )
}

export async function getServerSideProps () {
  const { eventsCategories } = await import('../data/data.json')
  console.log(eventsCategories)
  return {
    props: {
      data: eventsCategories
    }
  }
}
