import Head from 'next/head'

import { HomePage } from '../src/components/home/home-page'

export default function Home ({ data }) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage data={data} />

    </div>
  )
}

export async function getServerSideProps () {
  const { eventsCategories } = await import('../data/data.json')
  console.log(eventsCategories)
  return {
    props: {
      data: eventsCategories
    }
  }
}
